spring:
  application:
    name: hello
server:
  port: 3039

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetchRegistry: true
